### ISSUE TITLE
Becomes a partner to itself.

### ISSUE THREAD

**Issue by Praetoreean** [djphil/ospartner#1] opened 2018-05-10 22:18 UTC
A confirming request for partnership registers its own UUID in the database and becomes a partner to itself.
![2018-05-11_01-07-51](https://user-images.githubusercontent.com/10754213/39897016-0fd68506-54a0-11e8-8efe-622177df6010.jpg)
![2018-05-11_00-51-39](https://user-images.githubusercontent.com/10754213/39897017-10250b7c-54a0-11e8-8b83-11d15acd7777.jpg)

**Comment by djphil** [comment] 2018-05-11 22:01
I think this happens if the $ _SESSION ['useruuid'] is not the right one because normally your name should not appear in the "select form" of the possible choice of partner. This could happen in some cases if you use several "osmodules" but I'm not sure. I should know exactly when it happens. Can you tell me the steps to reproduce this problem?

**Comment by Praetoreean** [comment] 2018-05-11 23:28
Avatar's name did't appear in selection. Only another avatars. But as a result - in the world the avatar becomes a partner of oneself ...

login: bulk avatar
pass: test
url: http://caprica.1studi.ru/partner/

![screenshot from 2018-05-12 02-27-23](https://user-images.githubusercontent.com/10754213/39950739-08227f3a-5573-11e8-93eb-8a38299e2778.png)

**Comment by Praetoreean** [comment] 2018-05-11 23:49
One more time.
Sam Adama made a request to Caprica Cylon. Caprica accepted the request and eventually became a partner to herself ... )))

![2018-05-12_02-47-46](https://user-images.githubusercontent.com/10754213/39951056-e1467f80-5575-11e8-9294-938e733f0195.jpg)
![snapshot_003](https://user-images.githubusercontent.com/10754213/39951055-e0fba33e-5575-11e8-9fd9-39d0c8d6507a.png)


Lil' later, i delete partnership and make request from Caprica to Sam.
here is the base table:
![2018-05-12_02-52-44](https://user-images.githubusercontent.com/10754213/39951128-8fcd976e-5576-11e8-9fd3-a1dcb7ce67ce.jpg)

But inworld i still have same problem
![2018-05-12_02-54-08](https://user-images.githubusercontent.com/10754213/39951140-a62e7dde-5576-11e8-9680-543ce2bd92ff.jpg)

![snapshot_004](https://user-images.githubusercontent.com/10754213/39951330-53b42b74-5578-11e8-912a-c2006f2d1fcb.png)

**Comment by djphil** [comment] 2018-05-12 00:41
Fixed in c55e8e2874ffd2e9032a79919221cfea63f0934a, thank you for report.

**Comment by Praetoreean** [comment] 2018-05-12 03:16
Work fine! TYSM, Colleague!

![screenshot from 2018-05-12 06-15-45](https://user-images.githubusercontent.com/10754213/39953069-c8678988-5592-11e8-8819-04e2f36b0ecc.png)

**Closed as completed** 2018-05-12 03:57 UTC
Labels: bug, fixed
